---
# tasks file for add-rule

- name: Add rule to Palo Alto
  panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "{{ rule_name }}"
    description: "{{ description }}"
    source_zone: "{{ source_zone }}"
    destination_zone: "{{ dest_zone }}"
    source_ip: "{{ source_ip }}"
    source_user: "{{ source_user }}"
    destination_ip: "{{ dest_ip }}"
    category: "{{ category }}"
    application: "{{ application }}"
    service: "{{ service }}"
    hip_profiles: "{{ hip_profiles }}"
    action: 'allow'
    commit: 'False'
  when: paloalto == true or both == true

- name: Add rule to Juniper
  junos_config:
    provider: "{{ jun_provider }}"
    lines: "{{ jun_lines }}"
  when: juniper == true or both == true